### PR TITLE
Require clippy linting

### PR DESCRIPTION
**Pull request by encody**

### CODE REVIEW

**Comment by encody** [comment]
Note: the commit hook for clippy takes a nontrivial amount of time. On my machine, `cargo clippy` takes about 3 seconds to run, but when I use WSL (which I do frequently, in order to run workspaces tests), it takes about 20 seconds. I find this to be somewhat annoying. This is as compared to `cargo fmt -- --check`, which takes less than a second, even in WSL. What do we think - keep the commit hook (and the annoyance), or only run clippy on GH actions?

**Comment by ryancwalsh** [comment]
@encody  I haven't worked in Rust enough to have a strong opinion, but I'll say just generally that I do very much care about speed. 

E.g. I'll never code in Java again. It drove me crazy. Dealing with Rust compiling is annoying too, so I'd be careful about adding extra seconds on top of that. 

If Clippy offers a big benefit, it could be worth requiring it. But maybe we should just document it as a suggestion. Maybe there is some way to strongly encourage using it (manually) without requiring it.

Or maybe we can make it easily device-configurable as part of an env setting so that people can toggle it on or off.

**Comment by encody** [comment]
@ryancwalsh Okay, I'll remove the commit hook but leave the GitHub action.

**Review by ryancwalsh — APPROVED** [review]

**Review by nearken — APPROVED** [review]
LGTM

**Pull request merged**
