### PR TITLE
basic `cargo fmt -- --check` pre-commit hook

### PR DESCRIPTION
**Pull request by ryancwalsh**
@encody For https://near-foundation.atlassian.net/browse/ENG-149 , what do you think about this?

Adding a server-side CI tool looked more complicated than it's worth (for our small team at this point, I think).

### CODE REVIEW

**Comment by ryancwalsh** [comment]
@encody Also, maybe you should set up branch protection in this repo to prevent merges to `main` without approval. Let's have everything go into `develop` first.

**Comment by encody** [comment]
@ryancwalsh I no longer have admin access to this repo since I transferred it to the NEARFoundation org. You'll have to ask Robert to set that up.

**Comment by encody** [comment]
Two questions:

1. Why not simply have the hook run `cargo fmt` instead of telling you to run it? I think that's how husky (NPM) works.
2. I think the output is messing with the text formatting&mdash;removing the line breaks or something. The commit hook prints:

```txt
Please run `cargo fmt` before committing code. Here is the current result of `cargo fmt -- --check`:
Diff in /Users/jacob/Projects/near-contract-tools/src/standard/nep141.rs at line 22: #[derive(Serialize, Event)] #[event(standard = "nep141", version = "1.0.0", rename_all = "snake_case")] #[serde(untagged)] -pub enum Nep141Event<'a>{ +pub enum Nep141Event<'a> {  /// Token mint event. Emitted when tokens are created and total_supply is /// increased. - FtMint{ + FtMint {  /// Address to which new tokens were minted owner_id: &'a AccountId, /// Amount of minted tokens
```

When `cargo fmt -- --check` prints:

```txt
Diff in /Users/jacob/Projects/near-contract-tools/src/standard/nep141.rs at line 22:
 #[derive(Serialize, Event)]
 #[event(standard = "nep141", version = "1.0.0", rename_all = "snake_case")]
 #[serde(untagged)]
-pub enum Nep141Event<'a>{
+pub enum Nep141Event<'a> {
     /// Token mint event. Emitted when tokens are created and total_supply is
     /// increased.
-    FtMint{
+    FtMint {
         /// Address to which new tokens were minted
         owner_id: &'a AccountId,
         /// Amount of minted tokens
```

**Comment by ryancwalsh** [comment]
@encody  For 1, I was thinking of doing that since I'd like it handling it automatically, but I worried that there could be corner cases where someone has some modified files that are _not_ staged and are not intended to be part of the commit, and even those would be subject to `cargo fmt` making edits. Additionally, if somehow someone else managed to push unformatted code to a repo that you then pulled down, then some files that you didn't even work on and weren't thinking about would suddenly be modified automatically as part of this process. There might be some benefit to that being a more discrete/intentional action.

But I don't feel strongly. We could just choose to go with that auto approach if we like it.

For 2, I don't know off the top of my head why it's doing that, but I can explore. Having it print out perfectly is probably not important since we'll all be using IDEs anyway and the most important part is just the blocking of the commit, but yeah that's weird.

**Comment by encody** [comment]
Hm, I'm not sure I'm 100% on board with the idea of simply blocking the commits that don't conform. Seems like that could be something that is more of a hindrance than a help.

It doesn't look like `cargo fmt` or `rustfmt` support formatting individual files. Since the `cargo fmt -- --check` also applies to all files, I'm concerned that the "block the commit" hook would also apply in the situation you mentioned: where if someone pushes unformatted code, everyone else who pulls that code would be prevented from committing (outside of using `--force`) without formatting that code.

I've [added](https://github.com/NEARFoundation/near-contract-tools/pull/20/commits/62c3b1c5878e720bff76c023c0a3aff430ef1f76) an entry to the GH Actions file that _should_ check the formatting. This should simply prevent merging pull requests that contain unformatted code. Caveat: it's difficult (or, I don't know how) to test GH Actions files without simply merging to master and seeing what happens.

**Comment by encody** [comment]
Okay, looks like GH Actions is finally happy. Sorry for the barrage of "Run failed" emails.

**Pull request merged**
