### PR TITLE
Specify crate in every macro

### PR DESCRIPTION
**Pull request by encody**
serde uses this nifty field on their macros to allow you to specify the actual crate it should be using as the "serde" crate:

```rs
#[serde(crate = "path::to::serde")]
```

Emulating this pattern is useful:
 - Currently there is an inconsistent use of leading colons `::` in the macros
 - It's weird to try to use the `near_contract_tools_macros` in `near_contract_tools` for this reason
 - Some macros make use of other crates' types (`near_sdk` and `serde`, particularly). `near_sdk` reexports its own version of `serde`, so some users may wish to use that version (also we should discuss what the default serde crate should be @ryancwalsh @nearken).

### CODE REVIEW

**Comment by encody** [comment]
This PR enables writing code like this:

```rust
#[event(
    standard = "x-own",
    version = "1.0.0",
    // these two fields are the new ones
    crate = "crate",
    macros = "near_contract_tools_macros"
)]
```

## Important

*The vast majority of users will never need this feature. It is primarily useful for us, library developers, and people who may be using customized versions of the SDK, serde, or other crates.*

**Comment by encody** [comment]
I'm going to leave this PR up until @nearken and @ryancwalsh have a chance to review and respond, but once that happens I think this is the last necessary PR before the governance forum post.

**Comment by encody** [comment]
@ryancwalsh 

Okay, will update the docs. I consistently forget to update the public docs and keep just doing the internal ones. 🤦 

The `// darling` sections are pretty darling-specific; the tool [autodetects and injects those fields](https://github.com/TedDriggs/darling#features) (see: "**Auto-populated fields**").

The better names for `imp, ty, wher` would be `impl, type, where`, but those are all reserved words. This is just a symptom of the syntax of Rust: generic type variables declared on a type (like a struct or enum) can _generically_ appear in three places: immediately after the `impl` keyword (instantiation), immediately after the `type` name (use), and in the `where` clause (restraint). Since procedural macros like these can be applied to both generic and non-generic items, the `syn` parsing library conveniently packs all of the bits of syntax pertaining to generics into its `Generics` type, and provides the `split_for_impl` method for extracting the relevant chunks when recomposing the signature. Honestly, it's just a bit of boilerplate that works the same everywhere it appears.

A better name than `me` would be `crate`, but that's another reserved word. Maybe `crate_name`? `this`? `this_crate`? `the_crate`? `krate`? `self` is unfortunately another semi-reserved word.

**Review by ryancwalsh — APPROVED** [review]
@encody Ok, sounds good. No need to change `darling` or `me`.

**Pull request merged**
